name: deployment-pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ssh-strict: false
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build with Maven Project
        run: |
              mvn clean install -DskipTests
              mkdir deployment && cp target/*.jar src/main/resources/application.properties deployment
      - name: Copy Build and Configuration files to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.EC2_INSTANCE_TEST_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          #paraphrase: ${{secrets.EC2_PRIVATE_KEY_PARAPHRASE}}
          source: 'deployment/*,!deployment/*-sources.jar'
          target: '/home/ec2-user/best3deals'
      - name: Move build into deployment directory, restart service, clean up unused files and tail logs to monitor service restart
        env:
          HOSTNAME: ${{secrets.EC2_INSTANCE_TEST_HOST}}
          USER_NAME: ${{secrets.EC2_USER}}
          PRIVATE_KEY: ${{secrets.EC2_PRIVATE_KEY}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} \
          'pwd && sudo mv -f best3deals/deployment/*.jar /opt/apps/best3deals && \
          sudo service best3deals stop && \
          sudo service best3deals start && \
          sudo rm -rf best3deals'
